### PR TITLE
Show breaks in Content Catalogue

### PR DESCRIPTION
**Pull request by abhinayagarwal**
This PR adds registration and breaks in Content Catalogue.

image1image2image3

### CODE REVIEW

**Comment by stephanj** [comment]
Can you remove the room name where the break takes place, because that's only a placeholder.
So the sentence : "In Exhibition hall from 08:00 until 9:30" should be just  "from 08:00 until 9:30".

**Comment by abhinayagarwal** [comment]
Updated screenshot:

image

**Comment by stephanj** [comment]
image

**Comment by abhinayagarwal** [comment]
@stephanj Here are some images for your reference. Do you think they look good with orange and blue background?

bottomimage

**Pull request merged**
